/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FerestreTermopanBucurestiRouteImport } from './routes/ferestre-termopan-bucuresti'
import { Route as LegalRouteImport } from './routes/legal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FerestreTermopanBucurestiRoute =
  FerestreTermopanBucurestiRouteImport.update({
    id: '/ferestre-termopan-bucuresti',
    path: '/ferestre-termopan-bucuresti',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/ferestre-termopan-bucuresti': typeof FerestreTermopanBucurestiRoute
  '/legal': typeof LegalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/ferestre-termopan-bucuresti': typeof FerestreTermopanBucurestiRoute
  '/legal': typeof LegalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/ferestre-termopan-bucuresti': typeof FerestreTermopanBucurestiRoute
  '/legal': typeof LegalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/ferestre-termopan-bucuresti' | '/legal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/ferestre-termopan-bucuresti' | '/legal'
  id: '__root__' | '/' | '/contact' | '/ferestre-termopan-bucuresti' | '/legal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FerestreTermopanBucurestiRoute: typeof FerestreTermopanBucurestiRoute
  LegalRoute: typeof LegalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferestre-termopan-bucuresti': {
      id: '/ferestre-termopan-bucuresti'
      path: '/ferestre-termopan-bucuresti'
      fullPath: '/ferestre-termopan-bucuresti'
      preLoaderRoute: typeof FerestreTermopanBucurestiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FerestreTermopanBucurestiRoute: FerestreTermopanBucurestiRoute,
  LegalRoute: LegalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
